
name: C Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Make
        run: make

      - name: Run the program
        run: |
          echo -e "Toyota\n25000\nHonda\n22000\nBMW\n35000\nMercedes\n40000\nAudi\n30000\nLexus\n28000\nVolvo\n32000" | ./bin/program
